/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author crist
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Game() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casilla1 = new javax.swing.JButton();
        casilla2 = new javax.swing.JButton();
        casilla3 = new javax.swing.JButton();
        casilla4 = new javax.swing.JButton();
        casilla5 = new javax.swing.JButton();
        casilla6 = new javax.swing.JButton();
        casilla7 = new javax.swing.JButton();
        casilla8 = new javax.swing.JButton();
        casilla9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "3 en Raya\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casilla1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        casilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla1ActionPerformed(evt);
            }
        });
        jPanel1.add(casilla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 170));

        casilla2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(casilla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 180, 170));

        casilla3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(casilla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 180, 170));

        casilla4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(casilla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 170));

        casilla5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(casilla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 180, 170));

        casilla6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(casilla6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 180, 170));

        casilla7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(casilla7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 180, 170));

        casilla8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        casilla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla8ActionPerformed(evt);
            }
        });
        jPanel1.add(casilla8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 180, 170));

        casilla9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(casilla9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 180, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void casilla1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void casilla8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify
    public javax.swing.JButton casilla1;
    public javax.swing.JButton casilla2;
    public javax.swing.JButton casilla3;
    public javax.swing.JButton casilla4;
    public javax.swing.JButton casilla5;
    public javax.swing.JButton casilla6;
    public javax.swing.JButton casilla7;
    public javax.swing.JButton casilla8;
    public javax.swing.JButton casilla9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}